[package]
name = "easybill"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
easybill-rs = {git = "https://github.com/soenkeliebau/easybill-rs.git", branch = "main"}