[package]
name = "stackable-serious-business"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
reqwest = "0.12.14"
tokio = { version = "1.45.1", features = ["rt", "macros"] }
